version: '3.2'
services:
  traefik:
    image: traefik:v2.1
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.insecure=true
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic_conf

    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs/:/certs/:ro
      - ./traefik.yml:/etc/traefik/dynamic_conf/conf.yml:ro

  web:
    image: nginx
    labels:
      - traefik.enable=true
      - traefik.docker.network=default
      # http with redirection
      - traefik.http.middlewares.redirect-middleware.redirectscheme.scheme=https
      - traefik.http.routers.web-router.entrypoints=web
      - traefik.http.routers.web-router.rule=Host(`nginx.local`)
      - traefik.http.routers.web-router.middlewares=redirect-middleware
      # https
      - traefik.http.routers.websecure-router.entrypoints=websecure
      - traefik.http.routers.websecure-router.tls=true
      - traefik.http.routers.websecure-router.rule=Host(`nginx.local`)
  passit:
    image: nginx
    labels:
      - traefik.enable=true
      - traefik.docker.network=default
      # http with redirection
      - traefik.http.middlewares.redirect-middleware.redirectscheme.scheme=https
      - traefik.http.routers.passit-router.entrypoints=web
      - traefik.http.routers.passit-router.rule=Host(`passit.local`)
      - traefik.http.routers.passit-router.middlewares=redirect-middleware
      # https
      - traefik.http.routers.passitsecure-router.entrypoints=websecure
      - traefik.http.routers.passitsecure-router.tls=true
      - traefik.http.routers.passitsecure-router.rule=Host(`passit.local`)
      
